name: boutiqnet
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4 
  get: 

  firebase_core: ^1.15.0
 
  firebase_auth: ^3.3.18
  firebase_messaging: ^11.2.15
  cloud_firestore: 

#  ui
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  flutter_svg: ^1.0.3
  

  # grouped_list: ^4.1.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.1.2
  # crypto: ^3.0.2
  image_network:

dev_dependencies:
 
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter
    
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/


  fonts:
    - family: SourceSans
      fonts:
        - asset: assets/fonts/SourceSansPro.ttf
