// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJVONZAIEeMEo9tVXByDJ_QiDebaEO_fo',
    appId: '1:744821026615:web:d2c9604384861f3b5b74b2',
    messagingSenderId: '744821026615',
    projectId: 'boutiqne-b4260',
    authDomain: 'boutiqne-b4260.firebaseapp.com',
    storageBucket: 'boutiqne-b4260.appspot.com',
    measurementId: 'G-F23GHCJNRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9s65tHTack5CSB-9YV536us_PHZweXt4',
    appId: '1:744821026615:android:82c7018483e472ac5b74b2',
    messagingSenderId: '744821026615',
    projectId: 'boutiqne-b4260',
    storageBucket: 'boutiqne-b4260.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBudElphnYjxaeNjbduZFGjE1iPOKLFy0',
    appId: '1:744821026615:ios:a03640ed79ae2c935b74b2',
    messagingSenderId: '744821026615',
    projectId: 'boutiqne-b4260',
    storageBucket: 'boutiqne-b4260.appspot.com',
    androidClientId: '744821026615-ndsbma443c8on00g3eeilntetfhiqh1r.apps.googleusercontent.com',
    iosClientId: '744821026615-tfcrrtjlnk20obk8bn27jc8mstr6gur5.apps.googleusercontent.com',
    iosBundleId: 'com.example.boutiqne',
  );
}
